/*
 * EXTI.c
 *
 *  Created on: Dec 29, 2021
 *      Author: Radwa_Saeed
 * 	Edited on: Nov 18, 2023
 * 		By: rfAbedi
 */

#include "EXTI.h"


static unsigned int SYSCFG_EXTICR_EXTI[3][16] = {
	{SYSCFG_EXTICR1_EXTI0_PA, SYSCFG_EXTICR1_EXTI1_PA, SYSCFG_EXTICR1_EXTI2_PA, SYSCFG_EXTICR1_EXTI3_PA,
	 SYSCFG_EXTICR2_EXTI4_PA, SYSCFG_EXTICR2_EXTI5_PA, SYSCFG_EXTICR2_EXTI6_PA, SYSCFG_EXTICR2_EXTI7_PA,
	 SYSCFG_EXTICR3_EXTI8_PA, SYSCFG_EXTICR3_EXTI9_PA, SYSCFG_EXTICR3_EXTI10_PA, SYSCFG_EXTICR3_EXTI11_PA,
	 SYSCFG_EXTICR4_EXTI12_PA, SYSCFG_EXTICR4_EXTI13_PA, SYSCFG_EXTICR4_EXTI14_PA, SYSCFG_EXTICR4_EXTI15_PA},
	{SYSCFG_EXTICR1_EXTI0_PB, SYSCFG_EXTICR1_EXTI1_PB, SYSCFG_EXTICR1_EXTI2_PB, SYSCFG_EXTICR1_EXTI3_PB,
	 SYSCFG_EXTICR2_EXTI4_PB, SYSCFG_EXTICR2_EXTI5_PB, SYSCFG_EXTICR2_EXTI6_PB, SYSCFG_EXTICR2_EXTI7_PB,
	 SYSCFG_EXTICR3_EXTI8_PB, SYSCFG_EXTICR3_EXTI9_PB, SYSCFG_EXTICR3_EXTI10_PB, SYSCFG_EXTICR3_EXTI11_PB,
	 SYSCFG_EXTICR4_EXTI12_PB, SYSCFG_EXTICR4_EXTI13_PB, SYSCFG_EXTICR4_EXTI14_PB, SYSCFG_EXTICR4_EXTI15_PB},
	{SYSCFG_EXTICR1_EXTI0_PC, SYSCFG_EXTICR1_EXTI1_PC, SYSCFG_EXTICR1_EXTI2_PC, SYSCFG_EXTICR1_EXTI3_PC,
	 SYSCFG_EXTICR2_EXTI4_PC, SYSCFG_EXTICR2_EXTI5_PC, SYSCFG_EXTICR2_EXTI6_PC, SYSCFG_EXTICR2_EXTI7_PC,
	 SYSCFG_EXTICR3_EXTI8_PC, SYSCFG_EXTICR3_EXTI9_PC, SYSCFG_EXTICR3_EXTI10_PC, SYSCFG_EXTICR3_EXTI11_PC,
	 SYSCFG_EXTICR4_EXTI12_PC, SYSCFG_EXTICR4_EXTI13_PC, SYSCFG_EXTICR4_EXTI14_PC, SYSCFG_EXTICR4_EXTI15_PC}
};


void EXTI_EnableClock(void) {
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
}

void EXIT_INIT(int Port, int EXTx, char state) {
	SYSCFG->EXTICR[(int) EXTx/4] |= SYSCFG_EXTICR_EXTI[Port][EXTx];
	EXTI->IMR |= (1UL << EXTx);

	switch (state) {
		case (FALLING):
			EXTI->FTSR |= (1UL << EXTx);
			break;
		case (RISSING):
			EXTI->RTSR &= ~(1UL << EXTx);
			break;
	}
}

void NVIC_ConfigIRQ(int IRQn) {
	NVIC_SetPriority(IRQn, 0);
	NVIC_ClearPendingIRQ(IRQn);
	NVIC_EnableIRQ(IRQn);
}
