.MODEL SMALL
.STACK 64
.DATA
    STROUT DB 'ABCD'
.CODE  

MAIN    PROC FAR
    MOV AX, @DATA
    MOV DS, AX

    CALL TIMEOUT
        
    MOV AH, 4CH
    INT 21H
MAIN    ENDP


TIMEOUT PROC
    MOV AH, 2CH ;RETURN SYSTEM TIME [SECONDS] IN DH
    INT 21H

    MOV BH, DH
    INC BH ;SET END TIME WITH 1 SECOND DELAY
        
DELAYING:
        MOV AH, 2CH ;RETURN SYSTEM TIME [SECONDS] IN DH
        INT 21H
        CMP DH, BH
        JNE  DELAYING ;LOOP UNTIL CURRENT SYSTEM SECONDS REACH END TIME

    CALL PRINTSTRING

return:
    RET
TIMEOUT ENDP

PRINTSTRING PROC
    MOV CX, 04H ; COUNTER = Maximum length of String
    MOV DI, OFFSET STROUT

print:
        MOV DL, [DI] ;PRINT STROUT
        MOV AH, 02H
        INT 21H
        INC DI
        LOOP print

RET
PRINTSTRING ENDP

    END MAIN