.MODEL SMALL
.STACK 64
.DATA
    STROUT DB 'A'
.CODE  

MAIN    PROC FAR
    CALL TIMEOUT
        
    MOV AH, 4CH
    INT 21H
MAIN    ENDP


TIMEOUT PROC
    MOV AH, 2CH ;RETURN SYSTEM TIME [SECONDS] IN DH
    INT 21H

    MOV BH, DH
    INC BH ;SET END TIME WITH 1 SECOND DELAY
        
DELAYING:
        MOV AH, 2CH ;RETURN SYSTEM TIME [SECONDS] IN DH
        INT 21H
        CMP DH, BH
        JNE  DELAYING ;LOOP UNTIL CURRENT SYSTEM SECONDS REACH END TIME

    MOV DL, STROUT ;PRINT STROUT
    MOV AH, 02H
    INT 21H
    RET
TIMEOUT ENDP

    END MAIN